const express = require("express");
const router = express.Router();
const markController = require("../controllers/markController");
const { authenticate, authorize, requireSchoolContext } = require("../middleware/auth");
const { assertSchoolAccess } = require("../middleware/schoolAccess");
router.use(authenticate, requireSchoolContext, assertSchoolAccess);
router.get("/", authorize("super_admin", "school_admin", "dean", "teacher", "patron", "matron", "student"), markController.list);
router.post("/", authorize("teacher", "patron", "matron", "dean", "school_admin"), markController.create);
router.post("/bulk", authorize("teacher", "patron", "matron", "dean", "school_admin"), markController.bulkCreate);
router.delete("/:id", authorize("teacher", "patron", "matron", "dean", "school_admin"), markController.remove);
module.exports = router;
